apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: abp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: your-registry/api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__Default
          value: "Host=postgres;Database=abpdb;Username=postgres;Password=postgres"
        - name: Elasticsearch__Url
          value: "http://elasticsearch:9200"
        - name: Kafka__BootstrapServers
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: abp-app
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: abp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: your-registry/ui:latest
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: abp-app
spec:
  selector:
    app: ui
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: abp-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 80
  - host: ui.your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui
            port:
              number: 80 